FishingProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("authentication.urls")),
    path("", include("new_trip.urls")),
    path("", include("trips_feed.urls")),
    path("", include("catch_details.urls")),
    path("", include("stats.urls")),
    path("", include("user_profile.urls")),
    path("select2/", include("django_select2.urls")), # django-select2 
    path('', include('django.contrib.auth.urls')), # It's needed because of password reset
]#+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# for development
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authentication/urls.py
from django.urls import path, reverse_lazy
from . import views
from django.contrib.auth import views as auth_views
from .forms import UserPasswordResetForm, PasswordResetConfrimForm


app_name = "auth"
urlpatterns = [
    path("regisztráció/", views.register_view, name="register"),
    path("bejelentkezés/", views.login_view, name="login"),
    path("kijelentkezés/", views.logout_view, name="logout"),
    path("kapcsolat/", views.contact_view, name="contact"),
    
    # urls for password reset
    path("reset_password/", auth_views.PasswordResetView.as_view(
        template_name="authentication/password_reset.html",
        success_url=reverse_lazy('auth:password_reset_done'),
        form_class=UserPasswordResetForm,
    ), name="password_reset"), # Submit email form

    path("reset_password_sent/", auth_views.PasswordResetDoneView.as_view(
        template_name="authentication/password_reset_sent.html",
    ), name="password_reset_done"), # Email sent message

    path("reset/<uidb64>/<token>/", auth_views.PasswordResetConfirmView.as_view(
        success_url=reverse_lazy('auth:password_reset_complete'),
        template_name="authentication/password_reset_form.html",
        form_class=PasswordResetConfrimForm,
    ), name="password_reset_confirm"), # Link to password in email

    path("reset_password_complete/", auth_views.PasswordResetCompleteView.as_view(
        template_name="authentication/password_reset_complete.html",
    ), name="password_reset_complete"), # Password changed message
]

stats/urls.py
from django.urls import path
from . import views

app_name = "stats"
urlpatterns = [
    path("statisztika/<int:pk>/", views.StatView.as_view(), name="trip_stat"),

]

authentication/models.py
from django.db import models

authentication/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth.forms import PasswordResetForm, SetPasswordForm


class CreateUserForm(UserCreationForm): # Customizing UserCreationForm
    last_name = forms.CharField(max_length=70, widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'Vezetéknév', 
        }
    ))
    first_name = forms.CharField(max_length=70, widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'Keresztnév', 
        }
    ))
    username = forms.CharField(max_length=50, widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'Felhasználónév', 
        }
    ))
    email = forms.EmailField(widget=forms.EmailInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'Email', 
        }
    ),
    )
    password1 = forms.CharField(max_length=50, widget=forms.PasswordInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'Jelszó', 
        }
    ))
    password2 = forms.CharField(max_length=50, widget=forms.PasswordInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'Jelszó megerősítése', 
        }
    ))
    
    class Meta:
        model = User
        fields = ["username", "last_name", "first_name", "email", "password1", "password2"]
    

# Add styling to password reset form in the template
class UserPasswordResetForm(PasswordResetForm):
    def __init__(self, *args, **kwargs):
        super(UserPasswordResetForm, self).__init__(*args, **kwargs)

    email = forms.EmailField(label='', widget=forms.EmailInput(attrs={
        'class': 'form-control',
        'placeholder': 'Email',
        'type': 'email',
        'name': 'email'
        }))


class PasswordResetConfrimForm(SetPasswordForm):
    def __init__(self, *args, **kwargs):
        super(PasswordResetConfrimForm, self).__init__(*args, **kwargs)

    new_password1 = forms.CharField(
        label="Új jelszó",
        widget=forms.PasswordInput(attrs={
            'autocomplete': 'new-password',
            'class': 'form-control mb-2 mt-1',
            'type': 'password',
        }))

    new_password2 = forms.CharField(
        label="Új jelszó megerősítése",
        widget=forms.PasswordInput(attrs={
            'autocomplete': 'new-password',
            'class': 'form-control mb-2 mt-1',
            'type': 'password',
        }))

authentication/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from .forms import CreateUserForm
from django.contrib import messages
from django.views.generic.edit import FormView
from django.core.mail import send_mail


def register_view(request):
    form = CreateUserForm(request.POST or None)
    print(form.errors.as_data())
    if form.is_valid():
        form.save()
        user = form.cleaned_data.get("username")
        messages.success(request, f"Sikeres regisztráció. Jelentkezz be!")
        return redirect("auth:login")

    context = {"form": form}
    return render(request, "authentication/register.html", context)


def login_view(request):
    if request.user.is_authenticated: # detect if user is logged in
        messages.error(request, "Már be van jelentkezve.")
        return redirect("trips_feed:feed")
    
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect("trips_feed:home")
        else:
            messages.error(request, "A felhasználónév vagy a jelszó helytelen.")
    context= {}
    return render(request, "authentication/login.html", context)


def logout_view(request):
    logout(request)
    return redirect("auth:login")

"""
class ContactView(FormView):
    template_name = 'authentication/contact.html'
    form_class = CreateUserForm
    #success_url = '/thanks/'
"""

def contact_view(request):
    if request.method == "POST":
        message_name = request.POST.get("name")
        message_email = request.POST.get("email")
        message_subject = request.POST.get("subject")
        message_text = request.POST.get("message")

        # send an email
        send_mail(
            message_subject, # subject
            message_text, # message
            message_email, # from
            ['bence.janzso@gmail.com'], # to
        )
        messages.success(request, f"Köszönjük az üzeneted! Hamaorsan felvesszük veled a kapcsolatot.")

        return render(request, "authentication/contact.html", )

    context = {}
    return render(request, "authentication/contact.html", context)

authentication/templates/authentication/contact.html
{% extends "base.html" %}
{% block title %}Kapcsolat{% endblock %}

{% block content %}

<div class="row justify-content-center m-0">
    <div class="col-12 col-md-6 col-lg-4 p-0">
        <div class="m-3 text-center">
            {% if messages %}
            <div class="row justify-content-center m-0">
                <div class="col-10 col-md-8 p-0">
                {% for message in messages %}
                <!-- the message was sent -->
                    {% if message.tags == "success" %}
                    <div class="alert alert-success m-3 p-1" role="alert">
                        {{ message }}
                    </div>
                    {% endif %}
                {% endfor %}                    
                </div>
            </div>
            {% endif %}
        </div>
        
        <div class="row mx-3 my-3 justify-content-center text-center">
            <div class="card px-1 border-shadow">
                <h1 class="my-2" style="font-weight: 600; font-size:28px; color:#00754B">Küldj nekünk üzenetet!</h1>
                <div class="card-body">
                    <form method="POST" action="{% url 'auth:contact' %}">
                        {% csrf_token %}
                        <div class="row text-start">
                            <div class="col-12 mb-2">
                                <label class="form-label mb-1">Név:</label>
                                <input type="text" name="name" class="form-control" required>
                            </div>
                            <div class="col-12 mb-2">
                                <label class="form-label mb-1">Email:</label>
                                <input type="email" name="email" class="form-control" required>
                            </div>
                            <div class="col-12 mb-2">
                                <label class="form-label mb-1">Tárgy:</label>
                                <input type="text" name="subject" class="form-control" required>
                            </div>
                            <div class="col-12 mb-2">
                                <label class="form-label mb-1">Üzenet:</label>
                                <textarea name="message" class="form-control" rows="3" required></textarea>
                            </div>
                        </div>
        
                        <br>
                        <input type="submit" class="btn w-100" style="background-color: #00754B!important; color: #fff!important" value="Küldés">
                    </form>
                    
                </div><!--card body end-->
            </div><!--card end-->
        </div>
    </div> <!-- col end -->
</div> <!-- row end -->



{% endblock content %}

authentication/templates/authentication/login.html
{% extends "base.html" %}
{% block title %}Bejelentkezés{% endblock %}

{% block content %}

<div class="row justify-content-center m-0">
    <div class="col-12 col-md-6 col-lg-4 p-0">
        <!-- messages -->
        {% if messages %}
            <div class="row mx-3 my-3 justify-content-center text-center">        
                <div class="col-10 col-md-8 p-0">
                    {% for message in messages %}
                        <!-- incorrect username or password -->
                        {% if message.tags == "error" %}
                            <div class="alert alert-danger mb-3 p-1" role="alert">
                                {{ message }}
                            </div>
                        {% endif %}
                        <!-- the account was created -->
                        {% if message.tags == "success" %}
                        <div class="alert alert-success mb-3 p-1" role="alert">
                            {{ message }}
                        </div>
                        {% endif %}
                        <!-- need to be logged in -->
                        {% if message.tags == "info" %}
                        <div class="alert alert-info mb-3 p-1" role="alert">
                            {{ message }}
                        </div>
                        {% endif %}
                    {% endfor %}
                </div>
            </div>
        {% endif %}

        <div class="row mx-3 my-3 justify-content-center text-center">
            <div class="card px-1 border-shadow">
                <h1 class="my-2" style="font-weight: 600; font-size:28px; color:#00754B">Belépés</h1>
                <div class="card-body">
                    <form method="POST" action="">
                        {% csrf_token %}
                        <div class="input-group mb-3">
                            <span class="input-group-text">
                                <i class="bi bi-person"></i>
                            </span>
                            <input type="text" name="username" class="form-control" placeholder="Felhasználónév..." required>
                        </div>
                        <div class="input-group mb-3">
                            <span class="input-group-text">
                                <i class="bi bi-key"></i>
                            </span>
                            <input type="password" name="password" class="form-control" placeholder="Jelszó..." required>
                        </div>
                        <br>
                        <input type="submit" onclick="dataLayer.push({'event': 'login'});" class="btn w-100" style="background-color: #00754B!important; color: #fff!important" value="Belépés">
                    </form>
                    
                    <div class="row alert m-0">
                        <div class="col-sm-12">
                            Nincs fiókja?
                        </div>
                        <div class="col-sm-12">
                            <a href="{% url 'auth:register' %}" class="alert-link" style="color: #6A9A8B!important;">Regisztráció</a>
                        </div>
                        <div class="col-12 mt-2">
                            <a href="{% url 'auth:password_reset' %}" style="color: #00C6CF; font-weight:500">Elfejeltetted a jelszavad?</a>
                        </div>
                    </div> <!-- alert end -->
                </div><!--card body end-->
            </div><!--card end-->
        </div>
    </div>
</div>


{% endblock content %}

authentication/templates/authentication/password_reset.html
{% extends "base.html" %}
{% block title %}Jelszó visszaállítása{% endblock %}
{% block content %}


<div class="row m-3 justify-content-center text-center">
    <div class="col-12 col-md-8 col-lg-6 p-0">
        <h3 class="mb-3" style="font-size:28px; color:#00754B">Jelszó visszaállítása</h3>
        <p class="mb-4">Elfejeltetted a felszavad? Add meg az email címed és küldünk egy hivatkozást, amin keresztül új jelszót állíthatsz be.</p>
        <div class="row justify-content-center">
            <div class="col-12 col-md-6">
                <form method="POST">
                    {% csrf_token %}
                    {{ form }}
                    <br>
                    <input type="submit" value="küldés" class="btn w-50" style="background-color: #00754B!important; color: #fff!important">
                </form>
            </div>
        </div>
        
    </div>
</div>    


{% endblock content %}

authentication/templates/authentication/password_reset_complete.html
{% extends "base.html" %}
{% block title %}Jelszó beállítása{% endblock %}
{% block content %}
<div class="row m-3 justify-content-center text-center">
    <div class="col-12 col-md-8 col-lg-6 p-0">
        <h3 class="mb-3" style="font-size:28px; color:#00754B">Jelszó beállítása kész</h3>
        </div>
        <div class="col-12 p-0">
        <p class="mb-3">Jelszavad beállításra került. Most már bejelentkezhetsz.</p>
        <a href="{% url 'auth:login' %}" style="color: #6A9A8B;">Bejelentkezés</a>
    </div>
</div>

{% endblock content %}

authentication/templates/authentication/password_reset_form.html
{% extends "base.html" %}
{% block title %}Jelszó beállítása{% endblock %}
{% block content %}

<div class="row justify-content-center m-0">
    <div class="col-12 col-md-8 col-lg-6 p-0">
        <h3 class="m-3 text-center" style="font-size:28px; color:#00754B">Add meg az új jelszavad</h3>
        {% if form.errors %}
            <div class="row justify-content-center m-0 text-center">
                <div class="col-10 col-md-8 p-0">
                    <!-- error messages -->
                    {% for field, error in form.errors.items %}
                    <div class="alert alert-danger mb-3 p-1" role="alert">
                        {{ error|striptags }}
                    </div>
                    {% endfor %}
                </div>
            </div>
        {% endif %}

        <div class="row m-3 justify-content-center">
            <div class="col-12 col-md-8 p-0">
                <form method="POST">
                    {% csrf_token %}    
                    {{ form.new_password1.label }}:
                    {{ form.new_password1 }}
                    
                    {{ form.new_password2.label }}:
                    {{ form.new_password2 }}
                    <br>
                    <div class="m-0 text-center">
                        <input type="submit" value="küldés" class="btn w-50" style="background-color: #00754B!important; color: #fff!important">
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>


    

{% endblock content %}

authentication/templates/authentication/password_reset_sent.html
{% extends "base.html" %}
{% block title %}Jelszó visszaállítása{% endblock %}
{% block content %}
<div class="row m-3 justify-content-center text-center">
    <div class="col-12 col-md-8 col-lg-6 p-0">
        <h3 class="mb-3" style="font-size:28px; color:#00754B">Levél elküldve</h3>
        </div>
        <div class="col-12 p-0">
        <p class="mb-4">Elküldtük a hivatkozást a megadott email címre az új jelszó beállításához.</p>
    </div>
</div>

{% endblock content %}

authentication/templates/authentication/register.html
{% extends "base.html" %}
{% block title %}Regisztráció{% endblock %}
{% block content %}

<div class="row justify-content-center m-0">
    <div class="col-12 col-md-6 col-lg-4 p-0">
        <!-- error messages -->
        {% if form.errors %}
            <div class="row mx-3 my-3 justify-content-center text-center">    
                <div class="col-10 col-md-8 p-0">
                    {% for field, error in form.errors.items %}
                    <div class="alert alert-danger mb-3 p-1" role="alert">
                        {{ error|striptags }}
                    </div>
                    {% endfor %}
                </div>
            </div>
        {% endif %}

        <div class="row mx-3 my-3 justify-content-center text-center">
            <div class="card px-1 border-shadow">
                <h1 class="my-2" style="font-weight: 600; font-size:28px; color:#00754B">Regisztráció</h1>
                <div class="card-body">
                    <form method="POST" action="">
                        {% csrf_token %}
                        {{ form.non_field_errors }}
                        <div class="row justify-content-center m-0">
                            <div class="col-12 col-md-6 pe-md-1 p-0 mb-3">
                                <div class="input-group">
                                    <span class="input-group-text">
                                        <i class="bi bi-person-bounding-box"></i>
                                    </span>
                                    {{ form.last_name }}
                                </div>
                            </div>
                            <div class="col-12 col-md-6 ps-md-1 p-0 mb-3">
                                <div class="input-group">
                                    <span class="input-group-text">
                                        <i class="bi bi-person-bounding-box"></i>
                                    </span>
                                    {{ form.first_name }}
                                </div>
                            </div>
                            <div class="col-12 p-0 mb-3">
                                <div class="input-group">
                                    <span class="input-group-text">
                                        <i class="bi bi-person"></i>
                                    </span>
                                    {{ form.username }}
                                </div>
                            </div>
                            <div class="col-12 p-0 mb-3">
                                <div class="input-group">
                                    <span class="input-group-text">
                                        <i class="bi bi-envelope"></i>
                                    </span>
                                    {{ form.email }}
                                </div>
                            </div>
                            <div class="col-12 col-md-6 pe-md-1 p-0 mb-3">
                                <div class="input-group">
                                    <span class="input-group-text">
                                        <i class="bi bi-key"></i>
                                    </span>
                                    {{ form.password1 }}
                                </div>
                            </div>
                            <div class="col-12 col-md-6 ps-md-1 p-0 mb-3">
                                <div class="input-group">
                                    <span class="input-group-text">
                                        <i class="bi bi-key"></i>
                                    </span>
                                    {{ form.password2 }}
                                </div>
                            </div>
                        </div>

                        <br>
                        <input type="submit" onclick="dataLayer.push({'event': 'sign_up'});" class="btn w-100" style="background-color: #00754B!important; color: #fff!important" value="Regisztráció">
                    </form>
                    

                    <div class="row alert m-0 text-center">
                        <div class="col-sm-12">
                            Van már fiókja?
                        </div>
                        <div class="col-sm-12">
                            <a href="{% url 'auth:login' %}" class="alert-link" style="color: #6A9A8B!important;">Belépés</a>
                        </div>
                    </div> <!-- alert end -->
                </div><!--card body end-->
            </div><!--card end-->
        </div>
    </div> <!-- col-end -->
</div> <!-- row end -->


{% endblock content %}