FishingProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("authentication.urls")),
    path("", include("new_trip.urls")),
    path("", include("trips_feed.urls")),
    path("", include("catch_details.urls")),
    path("", include("stats.urls")),
    path("", include("user_profile.urls")),
    path("select2/", include("django_select2.urls")), # django-select2 
    path('', include('django.contrib.auth.urls')), # It's needed because of password reset
]#+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# for development
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catch_details/urls.py
from django.urls import path
from . import views

app_name = "catch_details"
urlpatterns = [
    path("fogás/<int:pk>/", views.CatchView.as_view(), name="catch"),
    path("fogás/<int:pk>/szerkesztés/", views.CatchUpdateView.as_view(), name="catch_update"),
    path("fogás/<int:pk>/törlés/", views.CatchDeleteView.as_view(), name="catch_delete"),
]

new_trip/urls.py
from django.urls import path
from . import views

app_name = "new_trip"
urlpatterns = [
    path("új_horgászat/", views.CreateTripView.as_view(), name="create_trip"),
    path("horgászat/<int:pk>/", views.TripDetailView.as_view(), name="trip_details"),
    path("horgászat/<int:pk>/új_fogás/", views.NewCatchView.as_view(), name="new_catch"),
    path("horgászat/<int:pk>/szerkesztés/", views.TripUpdateView.as_view(), name="edit_trip"),
    path("ajax/load-hookbaits/", views.load_hookbaits, name="ajax_load_hookbaits"), # for ajax
]

stats/urls.py
from django.urls import path
from . import views

app_name = "stats"
urlpatterns = [
    path("statisztika/<int:pk>/", views.StatView.as_view(), name="trip_stat"),

]

user_profile/urls.py
from django.urls import path
from . import views

app_name = "user_profile"
urlpatterns = [
    path("profil/<int:pk>/", views.ProfileView.as_view(), name="profile"),
    path("horgászatok/<int:pk>/", views.UserTripsView.as_view(), name="user_trips"),
    path("fogások/<int:pk>/", views.UserCatchesView.as_view(), name="user_catches"),
    #path("hookbait/create/", views.HookBaitCreateView.as_view(), name="hookbait_create"),
    path("profil/<int:pk>/csalik/", views.HookBaitUpdateView.as_view(), name="hookbaits"),
]

user_profile/models.py
from django.db import models
from new_trip.models import Fisherman

user_profile/forms.py
from django import forms
from new_trip.models import HookBait
from django.forms import modelformset_factory
"""
from .models import HookBait
from django.forms import modelformset_factory

class HookBaitForm(forms.ModelForm):

    class Meta:
        model = HookBait
        fields = ["name", "size", "taste"]
        widgets = {
            "name": forms.TextInput(attrs={'type': 'text', 'class': 'form-control', "placeholder": "Termék neve"}),
            "size": forms.TextInput(attrs={'type': 'text', 'class': 'form-control', "placeholder": "Méret"}),
            "taste": forms.TextInput(attrs={'type': 'text', 'class': 'form-control', "placeholder": "Íz"}),
        }
    

HookBaitFormset = modelformset_factory(HookBait, form=HookBaitForm, fields=["name", "size", "taste"], extra=1, can_delete=True)
"""
class HookBaitForm(forms.ModelForm):

    class Meta:
        model = HookBait
        fields = ["name"]
        widgets = {
            "name": forms.TextInput(attrs={'type': 'text', 'class': 'form-control', "placeholder": "Csali neve"}),
        }
    

HookBaitFormset = modelformset_factory(HookBait, form=HookBaitForm, fields=["name"], extra=1, can_delete=True)

user_profile/views.py
from django.shortcuts import render, redirect, reverse
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView
from new_trip.models import Fisherman, Trips, Catch, HookBait
#from .models import HookBait
from .forms import HookBaitForm, HookBaitFormset
from django.http import HttpResponse
from django.db.models import Sum
from django.views.generic.list import ListView


class ProfileView(DetailView):
    model = Fisherman
    template_name = "user_profile/profile.html"
    context_object_name = "profile"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # all related trips to the user
        context["all_trips"] = Trips.objects.filter(fisherman__user=self.request.user).count()

        # weight of all cathces
        """
        aggregation_weight = Catch.objects.filter(fisherman__user=self.request.user).aggregate(Sum('weight'))
        context["total_weight"] = aggregation_weight["weight__sum"]
        """
        # number of all catches
        context["all_catches"] = Catch.objects.filter(fisherman__user=self.request.user).count()

        # users's max catch
        context["max_catch"] = Catch.objects.filter(fisherman__user=self.request.user).order_by('-weight')[0:1]
        
        # List of own hookbaits
        context["own_hookbaits"] = HookBait.objects.filter(fisherman__user=self.request.user)

        return context 


class UserTripsView(ListView):
    model = Trips
    template_name = "user_profile/trips.html"
    context_object_name = "trips"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["user_trips"] = Trips.objects.filter(fisherman__user=self.request.user).order_by('-trip_id')
        return context


class UserCatchesView(ListView):
    model = Catch
    template_name = "user_profile/catches.html"
    context_object_name = "catches"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["user_catches"] = Catch.objects.filter(fisherman__user=self.request.user).order_by('-catch_id')
        return context


"""
class HookBaitCreateView(CreateView):
    model = HookBait
    template_name = "user_profile/hookbaits.html"
    form_class = HookBaitForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['formset'] = HookBaitFormset(queryset=HookBait.objects.none())
        return context
    
    def post(self, request, *args, **kwargs):
        formset = HookBaitFormset(request.POST)
        if formset.is_valid():
            return self.form_valid(formset)

    def form_valid(self, formset):
        instances = formset.save(commit=False)
        for instance in instances:
            instance.fisherman = self.request.user.fisherman
            instance.save()
        return super().form_valid(formset)

    def get_success_url(self):
        return reverse('user_profile:profile', args=(self.kwargs['pk'],))
"""

class HookBaitUpdateView(UpdateView):
    model = HookBait
    template_name = "user_profile/hookbaits.html"
    form_class = HookBaitForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['formset'] = HookBaitFormset(queryset=HookBait.objects.filter(fisherman=self.request.user.fisherman))
        return context

    def post(self, request, *args, **kwargs):
        formset = HookBaitFormset(request.POST)
        if formset.is_valid():
            return self.form_valid(formset)
        else:
            return self.form_invalid(formset)

    def form_valid(self, formset):
        instances = formset.save(commit=False)
        for instance in instances:
            instance.fisherman = self.request.user.fisherman
            instance.save()
        return super().form_valid(formset)

    def form_invalid(self, formset):
        return HttpResponse("Invalid")

    def get_success_url(self):
        return reverse('user_profile:profile', args=(self.kwargs['pk'],))

user_profile/templates/user_profile/catches.html
{% extends "base.html" %}
{% block title %}Fogások{% endblock %}
{% block content %}

<div class="row justify-content-center m-0">
    <div class="col-12 col-md-6 col-lg-4 p-0">
        <div class="row mx-3 mt-1">
            <div class="p-2" style="font-size: 22px; font-weight:600; color:#00754B">
                {{ request.user.username }} fogásai
            </div>
        </div>
        
        {% for catch in user_catches %}
        <div class="row justify-content-center mx-2 my-1">
            <div class="col-12 p-0">
                <div class="card m-2 border-shadow">
                    <a href="{% url 'catch_details:catch' catch.catch_id %}" class="text-decoration-none text-reset">
                        <div class="card-body p-2 mx-2 mx-md-4">
                            <div class="d-flex">
                                <div class="d-flex flex-column me-auto">
                                    <div style="font-size: 18px; font-weight:600; ">🐟 {{ catch.fish_type }}, {{ catch.weight }} Kg</div>
                                    <div class="py-1" style="font-size: 16px; font-weight:600; color:#00754B">🌊 {{ catch.trip.lake }}</div>
                                    <div style="font-size: 15px; font-weight:500; color:#6A9A8B">📅 {{ catch.datetime|date:"Y.m.d. H:i" }}</div>
                                </div>
                                <div class="align-self-center px-2">
                                    <i class="bi bi-chevron-right" style="font-size:18px;"></i>
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div> <!-- col end -->
</div> <!-- row end -->


{% endblock content %}

user_profile/templates/user_profile/hookbaits.html
{% extends "base.html" %}
{% load static %} <!-- It needs for jquery.formset reference -->
{% block title %}Csalik{% endblock %}
{% block content %}

<div class="row justify-content-center m-0">
    <div class="col-12 col-md-6 col-lg-4 p-0">
        <div class="row mx-3 my-3 justify-content-center text-center">
            <div class="card p-2 custom-borders">
                <div class="card-body p-2">
                    <form method="POST">
                        {% csrf_token %}
                        <table class="d-flex justify-content-center">
                            {{ formset.management_form }}
                            {% for form in formset %}
                            <tr class="formset_row">
                                {% for field in form.visible_fields %}
                                <td class="pb-2">
                                    <!-- Delete instance if that exists in the database -->
                                    {% if form.instance.pk %}{{ form.DELETE }}{% endif %}
                                    
                                    <!-- It's needed for the delete button will be in line with name field -->
                                    {% if forloop.first %}
                                    {% for hidden in form.hidden_fields %}
                                        {{ hidden }}
                                    {% endfor %}
                                    {% endif %}
        
                                    {{ field.errors }}
                                    {{ field }}
                                </td>
                                {% endfor %}
                            </tr>
                            {% endfor %}
                        </table>
                        <input type="submit" class="btn btn-primary w-50 mt-1" style="background-color: #00754B;" value="Mentés">
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>



<!-- scripts for formset -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script src="{% static 'js/jquery.formset.js' %}"></script>
<script type="text/javascript">
    $('.formset_row').formset({
        //addText: 'Hozzáad',
        //deleteText: 'Eltávolít',
        prefix: '{{ formset.prefix }}',
    });
</script>
{% endblock content %}

user_profile/templates/user_profile/profile.html
{% extends "base.html" %}
{% block title %}Profil{% endblock %}
{% block content %}

<div class="row justify-content-center m-0">
    <div class="col-12 col-md-6 col-lg-4 p-0">

        <div class="row mx-3 mt-1">
            <div class="p-2" style="font-size: 22px; font-weight:600; color:#00754B">
                <i class="bi bi-person-fill"></i>
                <span class="">{{ request.user.username }}</span>
            </div>
        </div>
        
        <div class="row justify-content-center mx-2">
            <div class="col-6 p-0">
                <div class="card m-2 border-shadow">
                    <a href="{% url 'user_profile:user_trips' request.user.fisherman.fisherman_id %}" class="text-decoration-none text-reset">
                        <div class="card-body text-center p-3">
                            <p class="m-0" style="font-size:22px; font-weight:600">{{ all_trips }} db <i class="bi bi-chevron-right" style="font-size:18px;"></i></p>
                            <p class="m-0" style="font-size:16px; font-weight:600; color:#6A9A8B">Horgászatok</p>
                        </div>
                    </a>
                </div>
            </div>
            <div class="col-6 p-0">
                <div class="card m-2 border-shadow">
                    <a href="{% url 'user_profile:user_catches' request.user.fisherman.fisherman_id %}" class="text-decoration-none text-reset">
                        <div class="card-body text-center p-3">
                            <p class="m-0" style="font-size:22px; font-weight:600">{{ all_catches  }} db <i class="bi bi-chevron-right" style="font-size:18px;"></i></p>
                            <p class="m-0" style="font-size:16px; font-weight:600; color:#6A9A8B">Fogott halak</p>
                        </div>
                    </a>
                </div>
            </div>
        </div>
        
        <div class="row mx-3">
            <div class="p-2" style="font-size: 20px; font-weight:600; color:#00754B">
                Legnagyobb fogás
            </div>
        </div>
        
        
        {% if max_catch.count == 0 %}
        <div class="row justify-content-center mx-2">
            <div class="col-12 p-0">
                <div class="card border-shadow m-2 p-0">
                    <div class="card-body p-1 py-3">
                        <div class="row text-center m-0">
                            <p class="m-0" style="font-size: 20px; font-weight:600;">Nincs még fogásod.</p>
                        </div>
                    </div>
                </div>
            </div>        
        </div>    
        {% else %}
            {% for catch in max_catch %}
            <div class="row justify-content-center mx-2">
                <div class="col-12 p-0">    
                    <div class="card border-shadow m-2 p-0" >
                        <a href="{% url 'catch_details:catch' catch.catch_id %}" class="text-decoration-none text-reset">
                            <div class="card-body p-1 py-3">
                                <div class="row text-center m-0">
                                    <div class="col-6">
                                        <img src="{{ catch.image.url }}" class="img-fluid border-shadow" alt="Fish">
                                    </div>
                                    <div class="col-6 d-flex justify-content-center p-0">
                                        <p class="m-0 align-self-center" style="font-size: 28px; font-weight:600; ">{{ catch.weight|floatformat:1 }} kg <i class="bi bi-chevron-right" style="font-size:22px;"></i></p>
                                    </div>
                                </div>
                            </div>
                        </a>
                    </div>
                </div>    
            </div>
            {% endfor %}
        {% endif %}
            
        
        <div class="row mx-3">
            <div class="p-2" style="font-size: 20px; font-weight:600; color:#00754B">
                Saját csalik <span class="px-1 tooltipClass" data-bs-placement="right" title="Itt tudod szerkeszteni a saját csalik listáját."><i class="bi bi-info-circle-fill" style="font-size: 20px; color:#3B3B3B"></i></span>
            </div>
        </div>
        
        <div class="row justify-content-center mx-2" >
            <div class="col-12 p-0">
                
                    {% if own_hookbaits.count == 0 %}
                    <ul class="list-group text-center m-2 p-0 border-shadow">
                        <a href="{% url 'user_profile:hookbaits' request.user.fisherman.fisherman_id %}" class="list-group-item list-group-item-action p-3" style="font-size: 20px; font-weight:600;">Nincs még saját csalid</a>        
                    </ul>
                    {% else %}
                    <ul class="list-group m-2 p-0">
                        <a class="border-shadow text-decoration-none" href="{% url 'user_profile:hookbaits' request.user.fisherman.fisherman_id %}">
                            {% for hookbait in own_hookbaits %}
                                <li class="list-group-item list-group-item-action p-2" style="font-size: 18px; font-weight:600;">
                                    <div class="d-flex justify-content-between">
                                        <div class="ps-2 ps-md-3">{{ hookbait.name }}</div>
                                        <div class="align-self-center pe-2 pe-md-3 ps-1">
                                            <i class="bi bi-chevron-right" style="font-size:18px;"></i>
                                        </div>
                                    </div>
                                </li>
                            {% endfor %}
                        </a>
                    </ul>
                    {% endif %}
                
            </div>
            
        </div>

    </div> <!-- col end -->
</div> <!-- row end -->

{% endblock content %}

user_profile/templates/user_profile/trips.html
{% extends "base.html" %}
{% block title %}Horgászatok{% endblock %}
{% block content %}

<div class="row justify-content-center m-0">
    <div class="col-12 col-md-6 col-lg-4 p-0">
        <div class="row mx-3 mt-1">
            <div class="p-2" style="font-size: 22px; font-weight:600; color:#00754B">
                {{ request.user.username }} horgászatai
            </div>
        </div>
        
        {% for trip in user_trips %}
        <div class="row justify-content-center mx-2 my-1">
            <div class="col-12 p-0">
                <div class="card m-2 border-shadow">
                    <a href="{% url 'new_trip:trip_details' trip.trip_id %}" class="text-decoration-none text-reset">
                        <div class="card-body p-2 mx-2 mx-md-4">
                            <div class="d-flex">
                                <div class="d-flex flex-column me-auto">
                                    <div style="font-size: 18px; font-weight:600; color:#00754B">🌊 {{ trip.lake }}</div>
                                    <div style="font-size: 15px; font-weight:500; color:#6A9A8B">📅 {{ trip.s_date|date:"SHORT_DATE_FORMAT" }}
                                        {% if not trip.s_date|date:"SHORT_DATE_FORMAT" == trip.e_date|date:"SHORT_DATE_FORMAT" %}
                                        - {{ trip.e_date|date:"SHORT_DATE_FORMAT" }}
                                        {% endif %}
                                    </div>
                                </div>
                                <div class="align-self-center px-2">
                                    <i class="bi bi-chevron-right" style="font-size:18px;"></i>
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div> <!-- col end -->
</div> <!-- row end -->

{% endblock content %}