FishingProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("authentication.urls")),
    path("", include("new_trip.urls")),
    path("", include("trips_feed.urls")),
    path("", include("catch_details.urls")),
    path("", include("stats.urls")),
    path("", include("user_profile.urls")),
    path("select2/", include("django_select2.urls")), # django-select2 
    path('', include('django.contrib.auth.urls')), # It's needed because of password reset
]#+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# for development
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catch_details/urls.py
from django.urls import path
from . import views

app_name = "catch_details"
urlpatterns = [
    path("fogás/<int:pk>/", views.CatchView.as_view(), name="catch"),
    path("fogás/<int:pk>/szerkesztés/", views.CatchUpdateView.as_view(), name="catch_update"),
    path("fogás/<int:pk>/törlés/", views.CatchDeleteView.as_view(), name="catch_delete"),
]

new_trip/urls.py
from django.urls import path
from . import views

app_name = "new_trip"
urlpatterns = [
    path("új_horgászat/", views.CreateTripView.as_view(), name="create_trip"),
    path("horgászat/<int:pk>/", views.TripDetailView.as_view(), name="trip_details"),
    path("horgászat/<int:pk>/új_fogás/", views.NewCatchView.as_view(), name="new_catch"),
    path("horgászat/<int:pk>/szerkesztés/", views.TripUpdateView.as_view(), name="edit_trip"),
    path("ajax/load-hookbaits/", views.load_hookbaits, name="ajax_load_hookbaits"), # for ajax
]

stats/urls.py
from django.urls import path
from . import views

app_name = "stats"
urlpatterns = [
    path("statisztika/<int:pk>/", views.StatView.as_view(), name="trip_stat"),

]

new_trip/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime
from PIL import Image, ExifTags
from io import BytesIO
from django.core.files import File



class Fisherman(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    fisherman_id = models.AutoField(primary_key=True)
    catch_sum_weight = models.DecimalField(max_digits=6, decimal_places=2, default=0)

    class Meta:
        verbose_name = "Fisherman"
        verbose_name_plural = "Fishermen"

    def __str__(self):
        return f'{self.user.username}'



class Trips(models.Model):
    lake = models.CharField("Lake", max_length=150)
    city = models.CharField("City", max_length=100, blank=True)
    s_date = models.DateTimeField("Starting Date", auto_now=False, auto_now_add=False)
    e_date = models.DateTimeField("Ending Date", auto_now=False, auto_now_add=False)
    fisherman = models.ManyToManyField(Fisherman)
    trip_id = models.AutoField(primary_key=True)
    total_catch_weight = models.DecimalField(max_digits=5, decimal_places=2, default=0)

    # it defines whether the trip is active or not.
    @property
    def is_active(self):
        if self.e_date.strftime('%Y/%m/%d %H:%M') > datetime.now().strftime('%Y/%m/%d %H:%M'):
            return True
        return False
    
    class Meta:
        verbose_name = "Trip"
        verbose_name_plural = "Trips"

    def __str__(self):
        return f"{self.lake} - {self.trip_id} - {self.s_date.strftime('%Y/%m/%d')}"



class HookBait(models.Model):
    hookbait_id = models.AutoField(primary_key=True)
    name = models.CharField('HookBait', max_length=120, blank=True, null=True)
    fisherman = models.ForeignKey(Fisherman, on_delete=models.CASCADE)

    class Meta:
        verbose_name = "Hookbait"
        verbose_name_plural = "Hookbaits"

    def __str__(self):
        return f"{self.name} - {self.hookbait_id}"


# Choices for catch
fish_choices = [
    ("Ponty", "Ponty"),
    ("Amur", "Amur"),
    ("Keszeg", "Keszeg"),
    ("Kárász", "Kárász"),
    ("Harcsa", "Harcsa"),
    ("Tok", "Tok"),
]

class Catch(models.Model):
    fish_type = models.CharField("Fish Type", max_length=50, choices=fish_choices, default="Carp")
    catch_id = models.AutoField(primary_key=True)
    weight = models.DecimalField("Weight", max_digits=5, decimal_places=2)
    length = models.DecimalField("Length", max_digits=5, decimal_places=2, blank=True, null=True)
    datetime = models.DateTimeField("Catch Time", auto_now=False, auto_now_add=False)
    image = models.ImageField(null=True, blank=True, default="default_img.png", upload_to="catch_images/")
    fisherman = models.ForeignKey(Fisherman, on_delete=models.CASCADE)
    trip = models.ForeignKey(Trips, on_delete=models.CASCADE)
    hookbait_name = models.CharField('Csali megnevezése', max_length=120, blank=True, null=True)
    hookbait = models.ForeignKey(HookBait, on_delete=models.SET_NULL, blank=True, null=True)

    class Meta:
        verbose_name = "Catch"
        verbose_name_plural = "Catches"
    
    # Reducing the size of images and rotate them, if it's necessary
    def save(self, *args, **kwargs):
        if self.image:
            img = Image.open(BytesIO(self.image.read()))
            
            if hasattr(img, '_getexif'):
                exif = img._getexif()
                if exif:
                    for tag, label in ExifTags.TAGS.items():
                        if label == 'Orientation':
                            orientation = tag
                            break
                    if orientation in exif:
                        if exif[orientation] == 3:
                            img = img.rotate(180, expand=True)
                        elif exif[orientation] == 6:
                            img = img.rotate(270, expand=True)
                        elif exif[orientation] == 8:
                            img = img.rotate(90, expand=True)

            img.thumbnail((1080,1080), Image.ANTIALIAS)
            output = BytesIO()
            img.save(output, format='JPEG', quality=95)
            output.seek(0)
            self.image = File(output, self.image.name) 

        return super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.fish_type}, {self.weight} kg - {self.trip.lake} - {self.datetime.strftime('%Y/%m/%d, %H:%M')}"

new_trip/views.py
from django.shortcuts import render, redirect, reverse
from django.contrib import messages
from .forms import TripsForm, CatchForm
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView
from .models import Trips, Fisherman, Catch, HookBait
from django.contrib.auth.decorators import login_required
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import UpdateView, DeleteView
from datetime import datetime

"""
#@login_required
def create_trip_view(request):
    if not request.user.is_authenticated:
            messages.info(request, 'Jelentkezz be az új túra létrehozásához.')
            return redirect("auth:login")
    
    actual_fisherman = request.user.fisherman
    for trip in actual_fisherman.trips_set.all():
        if trip.is_active == True:
            var = True
            return var
    if var:
        print("OK")
    else:
        if request.method == "POST":
            trip_form = TripsForm(request.POST)
            if trip_form.is_valid():
                if trip_form.cleaned_data:
                    trip = trip_form.save()
                return redirect(reverse("new_trip:trip_details", args=(trip.trip_id,)))
        else:
            trip_form = TripsForm()
        context = {
            "form": trip_form,
        }
        return render(request, "new_trip/create_trip.html", context)
"""

# Custom LoginRequiredMixin is needed to add alert message.
class CreateTripLoginRequiredMixin(LoginRequiredMixin):
    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            messages.info(request, 'Jelentkezz be az új horgászat létrehozásához.')
            return self.handle_no_permission()
        return super().dispatch(request, *args, **kwargs)

class CreateTripView(CreateTripLoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Trips
    form_class = TripsForm
    template_name = "new_trip/create_trip.html"
    success_message = "Horgásztúra sikeresen létrehozva."

    # it checks whether user has an active trip
    def has_active_trip(self):
        fisherman = self.request.user.fisherman
        for trip in fisherman.trips_set.all():
            if trip.is_active == True:
                return True
        return False

    # user is not able to create a new trip if he/she has already an existing one.
    def get(self, request, *args, **kwargs):
        if self.has_active_trip():
            # get id of the active trip
            active_trip_id = 0
            fisherman = self.request.user.fisherman
            for trip in fisherman.trips_set.all():
                if trip.is_active == True:
                    active_trip_id = trip.trip_id
                        
            messages.error(request, 'Van már egy aktív horgászatod.')
            return redirect('new_trip:trip_details', pk=active_trip_id)
        else:
            return super().get(request, *args, **kwargs)

    # checks whether any fishermen have an active trip. If yes the new trip cannot be created.
    def form_valid(self, form):
        for fisherman in form.cleaned_data["fisherman"]:
            for trip in fisherman.trips_set.all():
                if trip.is_active == True:
                    messages.error(self.request, 'Az egyik résztvevőnek van már aktív horgásztúrája.')
                    return redirect("trips_feed:feed")
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('new_trip:trip_details', args=(self.object.trip_id,))


class TripDetailView(DetailView):
    model = Trips
    template_name = "new_trip/trip_details.html"
    context_object_name = "trip"

    # get catches in the trip
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["catches"] = Catch.objects.filter(trip=self.kwargs.get('pk')).order_by('datetime')

        return context

    """
    For modal
    def post(self, *args, **kwargs):
        self.object = self.get_object(self.get_queryset())
        catch_form = CatchForm(self.request.POST)
        if catch_form.is_valid():
            if catch_form.cleaned_data:
                catch_form.instance.trip = self.object
                catch_form.save()
                return redirect(reverse("auth:home"))
            else:
                catch_form = CatchForm()
    """             

# Custom LoginRequiredMixin for new catch.
class NewCatchLoginRequiredMixin(LoginRequiredMixin):
    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            messages.info(request, 'Jelentkezzen be a fogás rögzítéséhez.')
            return self.handle_no_permission()
        return super().dispatch(request, *args, **kwargs)

class NewCatchView(NewCatchLoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Catch
    form_class = CatchForm
    template_name = "new_trip/new_catch.html"
    success_message = "Fogás rögzítve"
    
    # It checks whether the request user is in the trip.
    def is_in_trip(self):
        fishermen_in_trip = Fisherman.objects.filter(trips__trip_id=self.kwargs.get('pk'))
        for man in fishermen_in_trip:
            if man == self.request.user.fisherman:
                return True
        return False

    # It checks whether the fishing trip has ended.
    def is_trip_open(self):
        trip = Trips.objects.filter(trip_id=self.kwargs.get('pk'))
        for t in trip:
            if t.is_active == True:
                return True
        return False

    def get(self, request, *args, **kwargs):
        # checks whether the trip is open
        if self.is_trip_open():
            # checks wether the user in the trip
            if self.is_in_trip():
                return super().get(request, *args, **kwargs)
            else:
                messages.error(request, 'Nem rögzíhetsz fogást más horgászatán.')
                return redirect('new_trip:trip_details', pk=self.kwargs.get('pk'))
        else:
            messages.error(request, 'A horgászat lezárult. Már nem tudsz új fogásokat rögzíteni.')
            return redirect('new_trip:trip_details', pk=self.kwargs.get('pk'))
                
        
    # It lists those fishermen who attend at the trip
    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['fisherman'] = Fisherman.objects.filter(trips__trip_id=self.kwargs.get('pk'))
        return kwargs
    
    def form_valid(self, form):
        # It makes catch equal to the trip
        current_trip = Trips.objects.get(pk=self.kwargs['pk'])
        form.instance.trip = current_trip

        # Adding extra validation error: 
        if form.instance.hookbait_name != None and form.instance.hookbait != None:
            form.add_error("hookbait_name", "Csak egy csalit adhat meg!")
            form.add_error("hookbait", "Csak egy csalit adhat meg!")
            return super().form_invalid(form)

        # to add weight of the new catch to the total weight in Trips
        current_trip.total_catch_weight += form.instance.weight
        current_trip.save()

        # It adds cacth to the Fishermen total cacthes
        catcher = Fisherman.objects.get(fisherman_id=form.instance.fisherman_id) # by adding _id to the object, it gives the id
        catcher.catch_sum_weight += form.instance.weight
        catcher.save()

        # It creates a hookbait
        if not form.instance.hookbait_name == None:
            HookBait.objects.create(name=form.instance.hookbait_name, fisherman=form.instance.fisherman)

        if not form.instance.hookbait == None:
            form.instance.hookbait_name = form.instance.hookbait.name
            
        return super().form_valid(form)
    
    def get_success_url(self):
        return reverse('new_trip:trip_details', args=(self.kwargs['pk'],))


# Ajax for dependent select on the new catch page
def load_hookbaits(request):
    fisherman_id = request.GET.get("fisherman_id") # it is coming from the jquery script in the new catch page
    hookbaits = HookBait.objects.filter(fisherman_id=fisherman_id).order_by('name')
    return render(request, "new_trip/hookbaits_dependent_select.html", {"hookbaits": hookbaits})


class TripUpdateView(LoginRequiredMixin, UserPassesTestMixin, SuccessMessageMixin, UpdateView):
    model = Trips
    form_class = TripsForm
    template_name = "new_trip/create_trip.html"
    success_message = "Horgásztúra módosítva."

    # It limits that fishermen can only update the trips in which they are attending.
    def test_func(self):
        trip = self.get_object()
        for u in trip.fisherman.all():
            if self.request.user == u.user:
                return True
        return False

    def get_success_url(self):
        return reverse('new_trip:trip_details', args=(self.object.trip_id,))
    
"""
class TripDeleteView(LoginRequiredMixin, UserPassesTestMixin, SuccessMessageMixin, DeleteView):
    model = Trips
    template_name = ""

    # It limits that fishermen can only update the trips in which they are attending.
    def test_func(self):
        trip = self.get_object()
        for u in trip.fisherman.all():
            if self.request.user == u.user:
                return True
        return False

    def get_success_url(self):
        return reverse('trips_feed:feed')
"""

new_trip/templates/new_trip/create_trip.html
{% extends "base.html" %}
{% block title %}Új Horgászat{% endblock %}

{% block content %}
<!-- It's needed for ModelSelect2MultipleWidget (choosng multiple fishermen) -->
{{ form.media.css }}

<div class="row justify-content-center m-0">
    <div class="col-12 col-md-6 col-lg-4 p-0">
        <div class="row mx-3 my-3 justify-content-center">
            <div class="card px-1 border-shadow">
                <h3 class="mt-3 mb-1 text-center" style="font-weight: 600; font-size:28px; color:#00754B">Új Horgászat</h3>
                <h4 class="mt-3 mb-1 px-2 text-center" style="font-weight: 500; font-size:18px; color:#00754B">Hozz létre egy új horgászatot és kezd el rögzíteni a fogásaidat!</h4>
                <div class="card-body">
                <form method="POST" action="">
                    {% csrf_token %}
                    {{ form.non_field_errors }}
                    <div class="row justify-content-center mb-2">
                        <div class="col-sm-12">
                            <label for="LakeInput" class="form-label mb-1">Horgásztó:</label>
                            {% for error in form.lake.errors  %}
                            <p class="text-danger fw-bolder fst-italic fs-5 mb-1">
                                HIBA: {{ error }}                            
                            </p>
                            {% endfor %}
                            {{ form.lake }}
                        </div>
                    </div>
                    <div class="row justify-content-center mb-2">
                        <div class="col-sm-12">
                            <label for="CityInput" class="form-label mb-1">Település:</label>
                            {% for error in form.city.errors  %}
                            <p class="text-danger fw-bolder fst-italic fs-5 mb-1">
                                HIBA: {{ error }}                            
                            </p>
                            {% endfor %}
                            {{ form.city }}
                            <div class="form-text mt-1">Nem kötelező</div>
                        </div>
                    </div> <!-- Lake and City row end -->
                    <div class="row justify-content-center mb-2">
                        <div class="col-sm-12">
                            <label class="form-label mb-1" for="StartingDate">Kezdő dátum:</label>
                            {% for error in form.s_date.errors  %}
                            <p class="text-danger fw-bolder fst-italic fs-5 mb-1">
                                HIBA: {{ error }}                            
                            </p>
                            {% endfor %}
                            <div class="input-group mb-1">
                                {{ form.s_date }}
                                <span class="input-group-text">
                                    <i class="bi bi-calendar"></i>
                                </span>
                            </div>
                        </div>
                    </div>
                    <div class="row justify-content-center mb-2">
                        <div class="col-sm-12">
                            <label class="form-label mb-1" for="EndingDate">Záró dátum:</label>
                            {% for error in form.e_date.errors  %}
                            <p class="text-danger fw-bolder fst-italic fs-5 mb-1">
                                HIBA: {{ error }}                            
                            </p>
                            {% endfor %}
                            <div class="input-group">
                                {{ form.e_date }}
                                <span class="input-group-text">
                                    <i class="bi bi-calendar"></i>
                                </span>
                            </div>
                        </div>
                    </div> <!-- Dates row end -->
                    <div class="row justify-content-center mb-2">
                        <div class="col-sm-12">
                            <div class="col-sm-12">
                                <label for="LakeInput" class="form-label mb-1">
                                    Horgász(ok):
                                    <span class="px-1 tooltipClass" data-bs-placement="right" title="Csak regisztrált felhasználók vehetnek részt a horgászaton."><i class="bi bi-info-circle-fill" style="font-size: 18px; color:#3B3B3B"></i></span>
                                </label>
                                {% for error in form.fisherman.errors  %}
                                <p class="text-danger fw-bolder fst-italic fs-5 mb-1">
                                    HIBA: {{ error }}                            
                                </p>
                                {% endfor %}
                                {{ form.fisherman }}
                            </div>
                        </div>
                    </div> <!-- Fisherman row end -->
                    <hr>
                    <!-- form submit button -->
                    <input type="submit" onclick="dataLayer.push({'event': 'new_trip'});" class="btn w-100" style="background-color: #00754B!important; color: #fff!important" value="Beküld">
                </form>
                
                </div> <!-- card body end -->
            </div> <!--  card end -->
        </div> <!-- row end -->
    </div> <!-- col end -->
</div> <!-- row end -->

<!-- It's needed for ModelSelect2MultipleWidget (choosng multiple fishermen) -->
{{ form.media.js }}


{% endblock content %}

new_trip/templates/new_trip/hookbaits_dependent_select.html
<option value="">---------</option>
{% for hookbait in hookbaits %}
<option value="{{ hookbait.hookbait_id }}">{{ hookbait.name }}</option>
{% endfor %}

new_trip/templates/new_trip/trip_details.html
{% extends "base.html" %}
{% block title %}Horgászat{% endblock %}

{% block content %}

<div class="row justify-content-center m-0">
    <div class="col-12 col-md-6 col-lg-4 p-0">
        <!-- Summary table about the trip -->
        <div class="row justify-content-center m-2">
            <div class="card font-monospace p-2 mb-2  info-card">
                <div class="card-body position-relative p-0">
                    <div class="d-flex justify-content-center text-center my-1 mx-0" >
                        <h4 class="m-0" style="color: #00754B; font-size:22px; font-weight:600">{{ trip.lake }}</h4>    
                    </div>
                    <div class="d-flex flex-column text-center my-2">
                        <div class="mb-1" style="font-size: 16px;">📅Kezdés: <span style="color: #6A9A8B; font-size:15px">{{ trip.s_date|date:"Y.m.d. H:i" }}</span></div>
                        <div style="font-size: 16px;">📅Befejezés: <span style="color: #6A9A8B; font-size:15px">{{ trip.e_date|date:"Y.m.d. H:i" }}</span></div>
                    </div>
                    <div class="d-flex justify-content-center my-1">
                        <div class="align-self-center px-1" style="font-weight:500; font-size:16px">
                            {% if trip.fisherman.all.count == 1 %}
                            Horgász:
                            {% else %}
                            Horgászok:
                            {% endif %}
                        </div>
                        <div class="d-flex flex-wrap">
                            {% for fisherman in trip.fisherman.all %}
                            <div class="px-2 m-0" style="color: #00C6CF; font-weight:600; font-size:16px">
                                {{ fisherman }}
                            </div>
                            {% endfor %}
                        </div>
                    </div>

                    {% for fisherman in trip.fisherman.all %}
                    {% if fisherman.user == user %}
                    <!-- Edit Trip button -->
                    <div class="d-flex flex-row-reverse position-absolute top-0 end-0">
                        <a href="{% url 'new_trip:edit_trip' trip.trip_id %}" class="text-decoration-none text-reset p-1">
                            <svg xmlns="http://www.w3.org/2000/svg" width="23" height="23" fill="#00754B" class="bi bi-gear" viewBox="0 0 16 16">
                                <path d="M8 4.754a3.246 3.246 0 1 0 0 6.492 3.246 3.246 0 0 0 0-6.492zM5.754 8a2.246 2.246 0 1 1 4.492 0 2.246 2.246 0 0 1-4.492 0z"/>
                                <path d="M9.796 1.343c-.527-1.79-3.065-1.79-3.592 0l-.094.319a.873.873 0 0 1-1.255.52l-.292-.16c-1.64-.892-3.433.902-2.54 2.541l.159.292a.873.873 0 0 1-.52 1.255l-.319.094c-1.79.527-1.79 3.065 0 3.592l.319.094a.873.873 0 0 1 .52 1.255l-.16.292c-.892 1.64.901 3.434 2.541 2.54l.292-.159a.873.873 0 0 1 1.255.52l.094.319c.527 1.79 3.065 1.79 3.592 0l.094-.319a.873.873 0 0 1 1.255-.52l.292.16c1.64.893 3.434-.902 2.54-2.541l-.159-.292a.873.873 0 0 1 .52-1.255l.319-.094c1.79-.527 1.79-3.065 0-3.592l-.319-.094a.873.873 0 0 1-.52-1.255l.16-.292c.893-1.64-.902-3.433-2.541-2.54l-.292.159a.873.873 0 0 1-1.255-.52l-.094-.319zm-2.633.283c.246-.835 1.428-.835 1.674 0l.094.319a1.873 1.873 0 0 0 2.693 1.115l.291-.16c.764-.415 1.6.42 1.184 1.185l-.159.292a1.873 1.873 0 0 0 1.116 2.692l.318.094c.835.246.835 1.428 0 1.674l-.319.094a1.873 1.873 0 0 0-1.115 2.693l.16.291c.415.764-.42 1.6-1.185 1.184l-.291-.159a1.873 1.873 0 0 0-2.693 1.116l-.094.318c-.246.835-1.428.835-1.674 0l-.094-.319a1.873 1.873 0 0 0-2.692-1.115l-.292.16c-.764.415-1.6-.42-1.184-1.185l.159-.291A1.873 1.873 0 0 0 1.945 8.93l-.319-.094c-.835-.246-.835-1.428 0-1.674l.319-.094A1.873 1.873 0 0 0 3.06 4.377l-.16-.292c-.415-.764.42-1.6 1.185-1.184l.292.159a1.873 1.873 0 0 0 2.692-1.115l.094-.319z"/>
                            </svg>
                        </a>
                    </div>
                    {% endif %}
                    {% endfor %}
                </div> <!-- card body end -->
            </div> <!-- card end -->
        </div> <!-- row end -->

        <!-- Navigation for the trip -->
        <ul class="nav justify-content-center my-1">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'new_trip:new_catch' trip.trip_id %}"><button class="btn" style="background-color: #00754B!important; color: #fff!important">🎣 Új fogás</button></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'stats:trip_stat' trip.trip_id %}"><button class="btn" style="background-color: #00C6CF!important; color: #3B3B3B!important">📈 Statisztika</button></a>
            </li>
        </ul>

        <!-- Success message: catch was recorded message, catch was modified -->
        {% if messages %}
        <div class="row justify-content-center text-center m-0">
            <div class="col-10 col-md-8 p-0">
                {% for message in messages %}
                <!-- Success message: catch was recorded message, catch was modified -->
                {% if message.tags == "success" %}
                <div class="alert alert-success my-2 mx-3 p-1" role="alert">
                    {{ message }}
                </div>
                {% endif %}
                <!-- Error message:  -->
                {% if message.tags == "error" %}
                <div class="alert alert-danger my-2 mx-3 p-1" role="alert">
                    {{ message }}
                </div>
                {% endif %}
                {% endfor %}
            </div> <!-- col end -->
        </div> <!-- row end -->
        {% endif %}
        
        <!-- List of catches -->
        {% for catch in catches %}
        <div class="row justify-content-center mx-4 my-2">
            <div class="card p-2 mb-3 border-shadow">
                <a href="{% url 'catch_details:catch' catch.catch_id %}" class="text-decoration-none text-reset">
                    <div class="card-body p-0">
                        <div class="d-flex">
                            <div class="d-flex flex-column ps-2 pe-0 px-md-4 py-1 me-auto">
                                <div class="mb-1" style="font-size: 18px; font-weight:600">
                                    🐟 {{ catch.fish_type }}, {{ catch.weight }} Kg
                                </div>
                                <div >
                                    <span style="font-size: 15px; color:#6A9A8B">📅{{ catch.datetime|date:"m.d. H:i" }}</span>
                                    <span class="ps-1" style="font-size: 15px; color:#00C6CF; font-weight:600">🧍{{catch.fisherman}}</span>
                                </div>        
                            </div>
                            <div class="align-self-center pe-2">
                                <i class="bi bi-chevron-right" style="font-size:18px;"></i>
                            </div>
                        </div>
                    </div> <!-- card-body end -->
                </a>
            </div> <!-- card end -->
        </div> <!-- row end -->
        {% endfor %}

    </div> <!-- col end -->
</div> <!-- row end -->




{% endblock content %}