FishingProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("authentication.urls")),
    path("", include("new_trip.urls")),
    path("", include("trips_feed.urls")),
    path("", include("catch_details.urls")),
    path("", include("stats.urls")),
    path("", include("user_profile.urls")),
    path("select2/", include("django_select2.urls")), # django-select2 
    path('', include('django.contrib.auth.urls')), # It's needed because of password reset
]#+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# for development
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authentication/urls.py
from django.urls import path, reverse_lazy
from . import views
from django.contrib.auth import views as auth_views
from .forms import UserPasswordResetForm, PasswordResetConfrimForm


app_name = "auth"
urlpatterns = [
    path("regisztráció/", views.register_view, name="register"),
    path("bejelentkezés/", views.login_view, name="login"),
    path("kijelentkezés/", views.logout_view, name="logout"),
    path("kapcsolat/", views.contact_view, name="contact"),
    
    # urls for password reset
    path("reset_password/", auth_views.PasswordResetView.as_view(
        template_name="authentication/password_reset.html",
        success_url=reverse_lazy('auth:password_reset_done'),
        form_class=UserPasswordResetForm,
    ), name="password_reset"), # Submit email form

    path("reset_password_sent/", auth_views.PasswordResetDoneView.as_view(
        template_name="authentication/password_reset_sent.html",
    ), name="password_reset_done"), # Email sent message

    path("reset/<uidb64>/<token>/", auth_views.PasswordResetConfirmView.as_view(
        success_url=reverse_lazy('auth:password_reset_complete'),
        template_name="authentication/password_reset_form.html",
        form_class=PasswordResetConfrimForm,
    ), name="password_reset_confirm"), # Link to password in email

    path("reset_password_complete/", auth_views.PasswordResetCompleteView.as_view(
        template_name="authentication/password_reset_complete.html",
    ), name="password_reset_complete"), # Password changed message
]

new_trip/urls.py
from django.urls import path
from . import views

app_name = "new_trip"
urlpatterns = [
    path("új_horgászat/", views.CreateTripView.as_view(), name="create_trip"),
    path("horgászat/<int:pk>/", views.TripDetailView.as_view(), name="trip_details"),
    path("horgászat/<int:pk>/új_fogás/", views.NewCatchView.as_view(), name="new_catch"),
    path("horgászat/<int:pk>/szerkesztés/", views.TripUpdateView.as_view(), name="edit_trip"),
    path("ajax/load-hookbaits/", views.load_hookbaits, name="ajax_load_hookbaits"), # for ajax
]

stats/urls.py
from django.urls import path
from . import views

app_name = "stats"
urlpatterns = [
    path("statisztika/<int:pk>/", views.StatView.as_view(), name="trip_stat"),

]

trips_feed/urls.py
from django.urls import path
from . import views

app_name = "trips_feed"
urlpatterns = [
    path("horgászatok/", views.FeedView.as_view(), name="feed"),
    path("", views.HomeView.as_view(), name="home"),
]

user_profile/urls.py
from django.urls import path
from . import views

app_name = "user_profile"
urlpatterns = [
    path("profil/<int:pk>/", views.ProfileView.as_view(), name="profile"),
    path("horgászatok/<int:pk>/", views.UserTripsView.as_view(), name="user_trips"),
    path("fogások/<int:pk>/", views.UserCatchesView.as_view(), name="user_catches"),
    #path("hookbait/create/", views.HookBaitCreateView.as_view(), name="hookbait_create"),
    path("profil/<int:pk>/csalik/", views.HookBaitUpdateView.as_view(), name="hookbaits"),
]

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="Scofish">

    <title>Scofish | {% block title %} {% endblock %} | Horgász Alkalmazás</title>

    <meta name="description" content="A Scofish egy horgász alkalmazás, mellyel könnyedén számon tarthatod a fogásaidat és versenyezhetsz a barátaiddal, hogy ki fog több halat.">

    <meta name="keywords" content="horgász alkalmazás, horgász applikáció, alkalmazás horgászoknak, online fogási napló">

    <link rel="canonical" href="{{ request.path }}">

    <link rel="home" href="{% url 'trips_feed:home' %}">
    
    <!-- datalayer for Google Tag Manager -->
    <script>
      dataLayer = [];
    </script>
    <!-- Google Tag Manager -->
    <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
    new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
    j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
    'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
    })(window,document,'script','dataLayer','GTM-K732LLK');</script>
    <!-- End Google Tag Manager -->

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">

    <!-- Link for Bootstrap Icons -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.0/font/bootstrap-icons.css">

    <!-- Flatpickr link -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
    <!-- script for Hungarian language -->
    <script src="https://npmcdn.com/flatpickr/dist/flatpickr.min.js"></script>
    <script src="https://npmcdn.com/flatpickr/dist/l10n/hu.js"></script>
    
    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

    <!-- Chart.js -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.4.1/chart.min.js"></script>

    <!-- Google Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Bai+Jamjuree:ital,wght@1,600&family=Chakra+Petch&display=swap" rel="stylesheet">
    
    <!-- CSS link -->
    {% load static %}
    <link href="{% static '/css/style.css' %}" rel="stylesheet" type="text/css"/>
  </head>
  <body>
    <!-- Google Tag Manager (noscript) -->
    <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-K732LLK"
    height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
    <!-- End Google Tag Manager (noscript) -->
    
    <nav class="navbar navbar-expand-lg navbar-dark py-1 fixed-top main-navigation" >
      <div class="container-fluid">
        <a class="navbar-brand order-2 order-lg-1 me-auto me-lg-2 ms-1 ms-lg-0 p-1" href="{% url 'trips_feed:home' %}" id="BrandLogo">Scofish</a>
        <button class="navbar-toggler" type="button">
          <span class="navbar-toggler-icon"></span>
        </button>
        <!-- overlay -->
        <div class="overlay d-flex d-lg-none"></div>

        <div class="order-lg-2 d-flex flex-column flex-lg-row w-100 bp-3 pb-lg-0 sidebar">
          <ul class="navbar-nav me-lg-auto mt-2 mt-lg-0 mx-3 mx-lg-0 order-2 order-lg-1">

            <li class="nav-item">
              <a class="nav-link px-3 px-lg-2 active" aria-current="page" href="{% url 'trips_feed:home' %}">Főoldal</a>
            </li>
            <li class="nav-item">
              <a class="nav-link px-3 px-lg-2 active" aria-current="page" href="{% url 'trips_feed:feed' %}">Horgászatok</a>
            </li>
            <li class="nav-item">
              <a class="nav-link px-3 px-lg-2 active" aria-current="page" href="{% url 'new_trip:create_trip' %}">Új Horgászat</a>
            </li>
            <li class="nav-item">
              <a class="nav-link px-3 px-lg-2 active" aria-current="page" href="{% url 'auth:contact' %}">Kapcsolat</a>
            </li>
          </ul> <!-- Left navbar-nav end -->

          <ul class="navbar-nav mt-2 mt-lg-0 mx-3 mx-lg-0 order-1 order-lg-2">
            {% if request.user.is_authenticated %}
            <li class="nav-item dropdown order-lg-3 pt-2 p-lg-0">
              <a class="nav-link px-3 px-lg-2 py-1 dropdown-toggle active fst-italic fs-5" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                {{request.user.username}}
              </a>
              <ul class="dropdown-menu dropdown-menu-lg-end" aria-labelledby="navbarDropdown">
                <li><a class="dropdown-item" href="{% url 'user_profile:profile' request.user.fisherman.fisherman_id %}">Profil</a></li>
                <li><a class="dropdown-item" href="{% url 'auth:logout' %}">Kilépés</a></li>
              </ul>
            </li>
            {% endif %}
            
            {% if not request.user.is_authenticated %}
            <li class="nav-item order-lg-3 mt-2 m-lg-0">
              <a class="nav-link px-3 px-lg-2 py-1 py-lg-2 active" href="{% url 'auth:register' %}">Regisztráció</a>
            </li>
            <li class="nav-item order-lg-4 mb-2 m-lg-0">
              <a class="nav-link px-3 px-lg-2 py-1 py-lg-2 active" href="{% url 'auth:login' %}">Belépés</a>
            </li>
            {% endif %}            
          </ul> <!-- Right navbar-nav end -->
          
        </div>
        <!-- It shows the user's ongoing trip -->
        {% for trip in  request.user.fisherman.trips_set.all %}
          {% if trip.is_active %}
            <a class="btn navbar-brand order-3 order-lg-3 p-1 m-0  mx-lg-2" style="background-color: #f1f0f0!important; color: #00754B!important; font-size: 17px" href="{% url 'new_trip:trip_details' trip.trip_id %}">Aktuális Horgászat</a>
          {% endif %}
        {% endfor %}
      </div>
    </nav> <!-- navbar end -->
    
    <div class="container-fluid p-0" >
      {% block content %}
      
      {% endblock content %}
    </div>

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
    <!-- Enable tooltips -->
    <script>
      const tooltips = document.querySelectorAll('.tooltipClass')
      tooltips.forEach( t => {
          new bootstrap.Tooltip(t)
      })
    </script>
    <!-- Flactpickr script -->    
    <script>
      // This code activates flatpickr on fields with the 'datetimefield' class when the document has loaded
      window.addEventListener("DOMContentLoaded", function () {
          flatpickr(".datetimefield", {
              enableTime: true,
              dateFormat: "Y-m-d H:i",
              allowInput: false,
              disableMobile: true,
              time_24hr: true,
              position: 'auto',
              locale: 'hu'
          });
      });
    </script>
    
    <!-- Swiped-events -->
    <script src="{% static 'js/swiped-events.js' %}"></script>
    <!-- JS code for navbar -->
    <script src="{% static 'js/script.js' %}"></script>
  </body>
</html>